apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: project_payment-service:latest
        ports:
        - containerPort: 8005
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongodb-uri
        - name: RABBITMQ_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: rabbitmq-uri
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 8005
    targetPort: 8005
  type: ClusterIP
